apiVersion: v1
kind: Secret
metadata:
  name: db.secret
  namespace: std-java
type: Opaque
data:
  db_domain: cm0tMnplM2psandrOTZiY29waTQubXlzcWwucmRzLmFsaXl1bmNzLmNvbQ==
  db_user: azhzd2Vi 
  db_pwd: WXk0NTYxMjM=